/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LinhasRouteImport } from './routes/linhas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BairroSlugRouteImport } from './routes/bairro.$slug'
import { Route as LinhaIdRouteImport } from './routes/linha.$id'
import { Route as PontoIdRouteImport } from './routes/ponto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhasRoute = LinhasRouteImport.update({
  id: '/linhas',
  path: '/linhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BairroSlugRoute = BairroSlugRouteImport.update({
  id: '/bairro/$slug',
  path: '/bairro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhaIdRoute = LinhaIdRouteImport.update({
  id: '/linha/$id',
  path: '/linha/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoIdRoute = PontoIdRouteImport.update({
  id: '/ponto/$id',
  path: '/ponto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/linhas': typeof LinhasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bairro/$slug': typeof BairroSlugRoute
  '/linha/$id': typeof LinhaIdRoute
  '/ponto/$id': typeof PontoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/linhas': typeof LinhasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bairro/$slug': typeof BairroSlugRoute
  '/linha/$id': typeof LinhaIdRoute
  '/ponto/$id': typeof PontoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/linhas': typeof LinhasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/bairro/$slug': typeof BairroSlugRoute
  '/linha/$id': typeof LinhaIdRoute
  '/ponto/$id': typeof PontoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/linhas'
    | '/admin'
    | '/bairro/$slug'
    | '/linha/$id'
    | '/ponto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/linhas'
    | '/admin'
    | '/bairro/$slug'
    | '/linha/$id'
    | '/ponto/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/linhas'
    | '/_authenticated/admin'
    | '/bairro/$slug'
    | '/linha/$id'
    | '/ponto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LinhasRoute: typeof LinhasRoute
  BairroSlugRoute: typeof BairroSlugRoute
  LinhaIdRoute: typeof LinhaIdRoute
  PontoIdRoute: typeof PontoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linhas': {
      id: '/linhas'
      path: '/linhas'
      fullPath: '/linhas'
      preLoaderRoute: typeof LinhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/bairro/$slug': {
      id: '/bairro/$slug'
      path: '/bairro/$slug'
      fullPath: '/bairro/$slug'
      preLoaderRoute: typeof BairroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linha/$id': {
      id: '/linha/$id'
      path: '/linha/$id'
      fullPath: '/linha/$id'
      preLoaderRoute: typeof LinhaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto/$id': {
      id: '/ponto/$id'
      path: '/ponto/$id'
      fullPath: '/ponto/$id'
      preLoaderRoute: typeof PontoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LinhasRoute: LinhasRoute,
  BairroSlugRoute: BairroSlugRoute,
  LinhaIdRoute: LinhaIdRoute,
  PontoIdRoute: PontoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
